using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class letterList : MonoBehaviour
{
    // Start is called before the first frame update

    public characterInfo[] cList = new characterInfo[] {
        new characterInfo("w", "waaaaaaaa"), 
        new characterInfo("N", "neighbor"), 
        new characterInfo("4","feef"), 
        new characterInfo("c","anonymous"), 
        new characterInfo("]", "Hafflockman"), 
        new characterInfo("H", "Inverse colors gang"), 
        new characterInfo("<",":v)"), 
        new characterInfo("J","anonymous"),
        new characterInfo("u","feef"),
        new characterInfo(";","Bubble Letters Gang"),
        new characterInfo(";","Bubble Letters Gang"),
        new characterInfo(";","Föøp"),
        new characterInfo("g","Borff"),
        new characterInfo(";","homer pog"),
        new characterInfo("g","homie G"),
        new characterInfo("K","feef"),
        new characterInfo("^","bobby rosah"),
        new characterInfo("c","Fancy letter"),
        new characterInfo("i","Doge"),
        new characterInfo("b","b"),
        new characterInfo("%","da bug"),
        new characterInfo("2","handy man"),
        new characterInfo("B","Föøp"),
        new characterInfo("~","really huge brush gang"),
        new characterInfo("S","doge"),
        new characterInfo("7","funny"),
        new characterInfo("m","proletariat shackled by the woes of communism"),
        new characterInfo("#","unfunny middle schooler"),
        new characterInfo("1","Carlton Banks"),
        new characterInfo("0",":Prof:"),
        new characterInfo("s","Rattle snake harry"),
        new characterInfo("B","b"),
        new characterInfo("H","anonymous"),
        new characterInfo("X","Hafflockman"),
        new characterInfo("Z","zoom"),
        new characterInfo("G","da vinci"),
        new characterInfo("F","doge"),
        new characterInfo(";","anonymous"),
        new characterInfo("$","robbah"),
        new characterInfo("{","get distracted"),
        new characterInfo("]","Tempest"),
        new characterInfo("8","Analog gang"),
        new characterInfo("(","f"),
        new characterInfo("O","Block Letter Gang"),
        new characterInfo("D","Captain D"),
        new characterInfo("Z","Bubble Letters Gang"),
        new characterInfo("f","Sad f"),
        new characterInfo("N","don't say that one"),
        new characterInfo("F","anonymous"),
        new characterInfo("0","onion ring"),
        new characterInfo("m","anonymous"),
        new characterInfo("e","Hafflockman"),
        new characterInfo(".","theguy"),
        new characterInfo("U","Souja boy"),
        new characterInfo("=","peepee man"),
        new characterInfo("I","me"),
        new characterInfo("+","American"),
        new characterInfo("i","i"),
        new characterInfo("t","the pope"),
        new characterInfo("P","wahoo"),
        new characterInfo(":","blorp, eater of souls"),
        new characterInfo("n","anonymous"),
        new characterInfo("h","chair gang"),
        new characterInfo("5","anonymous"),
        new characterInfo("G","fella"),
        new characterInfo("k","ow"),
        new characterInfo("S","RunningZombie"),
        new characterInfo("B","Akboi12"),
        new characterInfo("l","Mig Moog"),
        new characterInfo("I","Pixar"),
        new characterInfo("o","JimmyCarlos"),
        new characterInfo("A","Delfrig"),
        new characterInfo("Y","oh no"),
        new characterInfo("!","Kojima"),
        new characterInfo("4","MrSlav999"),
        new characterInfo("^","MrSlav999"),
        new characterInfo("B","MrSlav999"),
        new characterInfo("*","MrSlav999"),
        new characterInfo("k","MrSlav999"),
        new characterInfo("?","MrSlav999"),
        new characterInfo("t","MrSlav999"),
        new characterInfo("q","jefvel"),
        new characterInfo("k","jefvel"),
        new characterInfo("[","Phaox05"),
        new characterInfo("A","Anonymous"),
        new characterInfo("M","Biscuiti"),
        new characterInfo("7","Biscuiti"),
        new characterInfo("l","Apple"),
        new characterInfo("<","Apple"),
        new characterInfo("@","Apple"),
        new characterInfo("H","Anonymous"),
        new characterInfo("8","Apple"),
        new characterInfo("\\","Anon E. Mouse"),
        new characterInfo("v","Anon E. Mouse"),
        new characterInfo("y","Anon E. Mouse"),
        new characterInfo("H","Anonymous"),
        new characterInfo("l","Anonymous"),
        new characterInfo("/","Michael Jackson"),
        new characterInfo("D","bored"),
        new characterInfo("@","Gary"),
        new characterInfo("k","Lesserstar"),
        new characterInfo("h","Myrmoth"),
        new characterInfo("X","Anonymous-Frog"),
        new characterInfo("D","Anonymous-Frog"),
        new characterInfo("#","Anonymous-Frog"),
        new characterInfo("M","Anonymous-Frog"),
        new characterInfo("<","crocodile man"),
        new characterInfo("x","I drew this with a touchpad"),
        new characterInfo("(","milkey63"),
        new characterInfo("p","Anonymous"),
        new characterInfo("5","Dungeonation"),
        new characterInfo("n","Anonymous-Frog"),
        new characterInfo("G","Anonymous-Frog"),
        new characterInfo("*","flower!"),
        new characterInfo("|","MrSlav999"),
        new characterInfo("b","note taker"),
        new characterInfo("n","not brian that's for sure"),
        new characterInfo("I","The Ides of March"),
        new characterInfo("S","Anonymous Contributor"),
        new characterInfo(",","mrman255"),
        new characterInfo("(","mrman255"),
        new characterInfo("b","Stepford"),
        new characterInfo("J","flip flip"),
        new characterInfo("t","Anonymous"),
        new characterInfo("8","Cyansquid21"),
        new characterInfo("D","Anonymous"),
        new characterInfo("X","FlyingParafin"),
        new characterInfo("G","Anonymous"),
        new characterInfo("Y","Yoda"),

    };
    


    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
